public: true
type: "docs"
title: "Creation, Maintenance and Use of Structured Rights Statements"
description: "Guidelines for the creation, maintenance, and use of structured rights"
pages:
  - ["Creation, Maintenance and Use of Structured Rights Statements", "index"]