public: true
type: "docs"
title: "Structured Rights Statements Guidelines"
description: "Guidelines for the creation, maintenance, and use of structured rights"
pages:
  - ["Structured Rights Statements Guidelines", "index"]